### PR TITLE
Update canget get canset set

### PR DESCRIPTION
**Pull request by joaquimg**

### CODE REVIEW

**Comment by mlubin** [comment]
Looks like there's an issue with the email used to make the commit.

**Comment by joaquimg** [comment]
Oh yeah, thats one of my emails from work. I fixed that for the next commits, there was a netrc file lost somewhere here.

**Comment by joaquimg** [comment]
If you think its important I can make a new PR

**Comment by mlubin** [comment]
Probably best to rebase or make a new PR to keep the contributor history clear.

**Comment by joaquimg** [comment]
replaced by #20

**Pull request closed without merging**
