### PR TITLE
Fix #24

### LINKED ISSUE #24: SingleVariable shortcut doesn't work
If you replace, e.g.,
https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/blob/249abf790eb75e673ee346e2952f3a6149e92254/test/instance.jl#L112
with 
```julia
vc3 = MOI.addconstraint!(m, v[3], MOI.EqualTo(0.0))
```
the test fails with an ambiguity warning:
```
  Got an exception of type MethodError outside of a @test
  MethodError: MathOptInterface.addconstraint!(::Instance{Float64}, ::MathOptInterface.VariableReference, ::MathOptInterface.EqualTo{Float64}) is ambiguous. Candidates:
    addconstraint!(m::MathOptInterfaceUtilities.AbstractInstance, f::F, s::S) where {F, S} in MathOptInterfaceUtilities at /home/mlubin/.julia/v0.6/MathOptInterfaceUtilities/src/instance.jl:141
    addconstraint!(m::MathOptInterface.AbstractInstance, v::MathOptInterface.VariableReference, set) in MathOptInterface at /home/mlubin/.julia/v0.6/MathOptInterface/src/constraints.jl:23
  Possible fix, define
    addconstraint!(::MathOptInterfaceUtilities.AbstractInstance, ::MathOptInterface.VariableReference, ::Any)
```

### PR DESCRIPTION
**Pull request by blegat**
Closes #24

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks, could you add a test?

**Comment by blegat** [comment]
Yes, but I will do that tomorrow, you can merge now if you want the fix sooner

**Comment by mlubin** [comment]
I can use the fix locally, so this isn't immediately blocking

**Comment by blegat** [comment]
Test added :)

**Pull request merged**
