### PR TITLE
Add canonical representation for affine

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by mlubin** [comment]
More comments please. What is defined as the canonical representation and how do these methods compute it?

**Comment by blegat** [comment]
@mlubin I have added documentation for `canonical`.
@joaquimg Any objection ? I have left your `isapprox` between `ScalarAffineFunction` of same coefficient type for now since it might be faster.

**Comment by joaquimg** [comment]
I am ok with that.

**Comment by mlubin** [comment]
Docs look good, thanks!

**Pull request merged**
